version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddd_twitter
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./apps/server/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-proot']
      interval: 5s
      timeout: 5s
      retries: 20
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: app
      DB_PASSWORD: password
      DB_NAME: ddd_twitter
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    volumes:
      - ./apps/server:/app/apps/server
      - /app/apps/server/node_modules
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      VITE_API_BASE: http://localhost:3000
    depends_on:
      - server
    ports:
      - '5173:5173'
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
volumes:
  db-data:
